const strings = {
  loginHead: ' Login',
  forgot_pass: 'Forgot Password',
  password: 'Password',
  number: 'Contact Number',
  create_account: 'Create new Account',
  Back_to_login: ' Back to Login',
  forgotPassText:
    'Please, enter your email address. You will receive a link to create a new password via email.',
  password: 'Password',
  send: 'send',
  email: 'Enter Email Id',
  next: 'NEXT->',
  previous: '<-PREVIOUS',
  GSTdetail: 'GST Details ',
  GSTNumber: 'GST Number',
  GSTcetificate: 'Upload GST Certificate',
  signature: 'Upload Signature ',
  digital_signature: 'Create Digital Signature',
  Pickup_address: 'Pickup Address',
  profile_pic: 'Select Profile Pic',
  Company_Name: 'Company/Firm Name',
  shopnumber: 'Shop no./Building.',
  colonyname: 'Street/Colony',
  landmark_name: 'Landmark',
  pincode: 'Pincode',
  manufacturer_email: 'Manufacturer Email',
  Manufacturer_details: 'Manufacturer Details',
  manufacturer_name: 'Contact Person Name',
  password_guideline:
    'The password must be at least 8 characters long with at least one uppercase, one special character and one number (like - Beparr@123)',
};
export default strings;
